#region CPL License
/*
Nuclex Framework
Copyright (C) 2002-2009 Nuclex Development Labs

This library is free software; you can redistribute it and/or
modify it under the terms of the IBM Common Public License as
published by the IBM Corporation; either version 1.0 of the
License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
IBM Common Public License for more details.

You should have received a copy of the IBM Common Public
License along with this library
*/
#endregion

using System;
using System.Collections.Generic;

using Nuclex.Graphics.Batching;
using Nuclex.Graphics.SpecialEffects.Particles.HighLevel;

namespace Nuclex.Graphics.SpecialEffects.Trails {

#if false
  /// <summary>Renders a trail for particles that store their past positions</summary>
  /// <typeparam name="ParticleType">
  ///   Type of particles whose trail will be rendered
  /// </typeparam>
  public class TrailRenderer<ParticleType> :
    IParticleRenderer<ParticleType, TrailVertex>
    where ParticleType : struct {

    /// <summary>Renders a series of particles</summary>
    /// <param name="particles">Particles that will be rendered</param>
    /// <param name="primitiveBatch">
    ///   Primitive batch that will receive the vertices generated by the particles
    /// </param>
    public void Render(
      ArraySegment<ParticleType> particles,
      PrimitiveBatch<TrailVertex> primitiveBatch
    ) {
      
    }

  }
#endif

} // namespace Nuclex.Graphics.SpecialEffects.Trails
